# Generated by Django 3.2.9 on 2021-11-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20211121_1517"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliationrecord",
            old_name="user_financial",
            new_name="user",
        ),
    ]
