# Generated by Django 3.2.9 on 2021-11-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_user_financial_affiliationrecord_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliationrecord",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="affiliationrecord",
            old_name="product_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="affiliationrecord",
            old_name="product_sale_price",
            new_name="sale_price",
        ),
    ]
