# Generated by Django 3.2.9 on 2021-11-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFinancial",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="financial",
                        serialize=False,
                        to="auth.user",
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "sheba",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="شماره شبا"
                    ),
                ),
                (
                    "card_num",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="شماره کارت"
                    ),
                ),
                ("credit", models.IntegerField(default=0, verbose_name="اعتبار")),
            ],
            options={
                "verbose_name": "اطلاعات مالی",
                "verbose_name_plural": "اطلاعات مالی",
            },
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="مبلغ")),
                (
                    "type",
                    models.CharField(
                        choices=[("D", "کسر اعتبار"), ("I", "افزایش اعتبار")],
                        max_length=50,
                        verbose_name="نوع عملیات",
                    ),
                ),
                (
                    "user_financial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_record",
                        to="financial.userfinancial",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوابق مالی",
                "verbose_name_plural": "سوابق مالی",
            },
        ),
    ]
