# Generated by Django 3.2.9 on 2021-11-18 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ"
            ),
        ),
    ]
