# Generated by Django 3.2.9 on 2021-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_financialrecord_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
        ),
    ]
