# Generated by Django 4.2.10 on 2024-03-23 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0005_rename_affiliationrecord_affiliatorproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="لید")),
                (
                    "phoneNo",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, null=True, verbose_name="قیمت"),
                ),
                (
                    "sale_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت حراج"
                    ),
                ),
                (
                    "affiliator_share",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="سهم افلییتور"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "جدید"),
                            ("F", "تماس"),
                            ("R", "رد"),
                            ("B", "پرداخت اولیه"),
                            ("G", "بازگشت وجه به علت گارانتی"),
                            ("F", "خرید نهایی"),
                        ],
                        default="N",
                        max_length=5,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "affiliator_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_lead",
                        to="product.affiliatorproduct",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لید",
                "verbose_name_plural": "لیدها",
                "ordering": ["-id"],
            },
        ),
    ]
